# Generated by Django 3.1.2 on 2020-10-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatitos',
            fields=[
                ('id', models.IntegerField(help_text='Ingrese ID del gato', primary_key=True, serialize=False)),
                ('nombre', models.TextField(help_text='Ingrese nombre del gato')),
                ('edad', models.IntegerField(help_text='Ingrese edad del gato', max_length=2)),
                ('carac', models.TextField(help_text='Ingrse caracteristicas del gato', max_length=1000)),
            ],
        ),
    ]
