# Generated by Django 3.1.2 on 2020-10-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatitos',
            name='edad',
            field=models.IntegerField(help_text='Ingrese edad del gato'),
        ),
        migrations.AlterField(
            model_name='gatitos',
            name='nombre',
            field=models.TextField(help_text='Ingrese nombre del gato', max_length=50),
        ),
    ]
