# Generated by Django 3.1.2 on 2020-10-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0002_auto_20201021_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatitos',
            name='carac',
            field=models.TextField(help_text='Ingrese caracteristicas del gato', max_length=1000),
        ),
    ]
