# Generated by Django 3.1.2 on 2020-10-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0004_auto_20201028_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('rut', models.CharField(help_text='Ingrese Rut del Donante', max_length=9, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ingrese Nombre del Donante', max_length=50)),
                ('monto', models.IntegerField(help_text='Ingrese el monto a Donar')),
                ('fono', models.IntegerField(help_text='Ingrese telefono de contacto')),
                ('mensaje', models.TextField(help_text='Dejanos un mensaje de cariño', max_length=1000)),
                ('correo', models.CharField(help_text='Ingrese Correo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('rut', models.CharField(help_text='Ingrese Rut del nuevo Socio', max_length=9, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ingrese Nombre del nuevo Socio', max_length=50)),
                ('monto', models.IntegerField(help_text='Ingrese el monto a Donar Mensualmente')),
                ('fono', models.IntegerField(help_text='Ingrese telefono de contacto')),
                ('mensaje', models.TextField(help_text='Dejanos un mensaje de cariño', max_length=1000)),
                ('correo', models.CharField(help_text='Ingrese Correo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('rut', models.CharField(help_text='Ingrese Rut del Nuevo Voluntario', max_length=9, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ingrese Nombre del Nuevo Voluntario', max_length=50)),
                ('fono', models.IntegerField(help_text='Ingrese telefono de contacto')),
                ('correo', models.CharField(help_text='Ingrese Correo', max_length=100)),
            ],
        ),
    ]
