# Generated by Django 3.1.2 on 2020-10-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0005_donar_socio_voluntario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(help_text='Ingrese Rut ', max_length=9, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ingrese Nombre', max_length=50)),
                ('contra', models.CharField(help_text='Ingrese Contraseña', max_length=100)),
                ('fono', models.IntegerField(help_text='Ingrese telefono de contacto')),
                ('correo', models.CharField(help_text='Ingrese Correo', max_length=100)),
                ('cate', models.CharField(help_text='Ingrese si es Donador, Socio o Voluntario', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Donar',
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
        migrations.DeleteModel(
            name='Voluntario',
        ),
    ]
