# Generated by Django 3.1.2 on 2020-11-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0008_auto_20201103_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padres',
            options={'ordering': ['nom']},
        ),
        migrations.RemoveField(
            model_name='padres',
            name='id',
        ),
        migrations.AddField(
            model_name='padres',
            name='idgatos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gatos.gatitos'),
        ),
    ]
