# Generated by Django 3.1.2 on 2020-11-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0009_auto_20201104_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatitos',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nom']},
        ),
        migrations.AlterField(
            model_name='gatitos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenesgato/'),
        ),
    ]
