# Generated by Django 3.1.2 on 2020-11-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0010_auto_20201105_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatitos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesgato/'),
        ),
    ]
