# Generated by Django 3.1.2 on 2020-11-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0011_auto_20201105_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
